if Legacy.Basher then
  cecho("\n<ansi_yellow>Rage Configuration for: <white>"..gmcp.Char.Status.class:upper().."\n\n")
  
  cecho("<ansi_yellow>Use Big Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage.."%<ansi_yellow> enemy health.")
  cechoLink("<green>  ^  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage + 1 cecho("\n<ansi_yellow>Use Big Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage.."%<ansi_yellow> enemy health.")end, "Increase the value by 1%", true)
  cechoLink("<green>^^  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage + 5 cecho("\n<ansi_yellow>Use Big Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage.."%<ansi_yellow> enemy health.")end, "Increase the value by 5%", true)
  cechoLink("<red>v  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage - 1 cecho("\n<ansi_yellow>Use Big Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage.."%<ansi_yellow> enemy health.")end, "Decrease the value by 1%", true)
  cechoLink("<red>vv  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage - 5 cecho("\n<ansi_yellow>Use Big Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.bigDamage.."%<ansi_yellow> enemy health.")end, "Decrease the value by 5%", true)

  cecho("\n\n<ansi_yellow>Use Small Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage.."%<ansi_yellow> enemy health.")
  cechoLink("<green>  ^  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage + 1 cecho("\n<ansi_yellow>Use Small Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage.."%<ansi_yellow> enemy health.")end, "Increase the value by 1%", true)
  cechoLink("<green>^^  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage + 5 cecho("\n<ansi_yellow>Use Small Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage.."%<ansi_yellow> enemy health.")end, "Increase the value by 5%", true)
  cechoLink("<red>v  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage - 1 cecho("\n<ansi_yellow>Use Small Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage.."%<ansi_yellow> enemy health.")end, "Decrease the value by 1%", true)
  cechoLink("<red>vv  ", function() Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage = Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage - 5 cecho("\n<ansi_yellow>Use Small Damage rage above <white>"..Legacy.Settings.Basher.Classes[gmcp.Char.Status.class].configRage.smallDamage.."%<ansi_yellow> enemy health.")end, "Decrease the value by 5%", true)

end